Makefile
charts/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml
cmd/manager/main.go

Cherry pick mar 10

---

api/v1alpha1/managedserviceaccount_types.go
charts/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml
config/crd/bases/authentication.open-cluster-management.io_managedserviceaccounts.yaml

(`git cherry-pick b8d1b0bff9ef3d4a8c568069b93410a3b4917afe`)
* typo fix and description review
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
* forgot to ran manifests
Signed-off-by: Nathan Weatherly <nweather@redhat.com>

typo fix and description review (#31)

---

README.md

Signed-off-by: Brian Smith briansmi@redhat.com

Trigger rebuild for MCE 2.1

---

sonar-project.properties

Signed-off-by: xuezhaojun <zxue@redhat.com>

Fix wrong exclusion paths in sonar config

---

pkg/addon/manager/addon_test.go
pkg/addon/manager/manifests/templates/image_pull_secret.yaml
pkg/addon/manager/manifests/templates/namespace.yaml

issue reference: 
- https://issues.redhat.com/browse/ACM-6864?focusedId=22811617&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22811617
- https://issues.redhat.com/browse/ACM-7114

[backplane-2.3] orphan the agent install namespace

---

.tekton/managed-serviceaccount-zbkr-pull-request.yaml
.tekton/managed-serviceaccount-zbkr-push.yaml
Dockerfile.rhtap

issue reference: https://issues.redhat.com/browse/ACM-7262

:seedling: Add dockerfile for rhtap

---

pkg/addon/manager/addon_test.go
pkg/addon/manager/manifests/templates/image_pull_secret.yaml
pkg/addon/manager/manifests/templates/namespace.yaml

issue reference: https://issues.redhat.com/browse/ACM-7115

[bp-2.2] orphan the agent install namespace

---

.tekton/managed-serviceaccount-mce-25-pull-request.yaml
.tekton/managed-serviceaccount-mce-25-push.yaml

Konflux migration from 0.3 to 0.4

---

Dockerfile.rhtap

:seedling:  update dockerfile.rhtap

---

.tekton/managed-serviceaccount-mce-26-pull-request.yaml
.tekton/managed-serviceaccount-mce-26-push.yaml

[bp-2.6]konflux: migration from 0.1 to 0.2

---

.tekton/managed-serviceaccount-mce-25-pull-request.yaml
.tekton/managed-serviceaccount-mce-25-push.yaml

[2.5] konflux migration to 0.2

---

pkg/addon/agent/controller/token.go
pkg/addon/agent/controller/token_test.go

* Check if the token has expired periodically
* Requeue before the token is about to expire
* Add unit tests
---------
Fixes #https://issues.redhat.com/browse/ACM-14261
Related PR: https://github.com/open-cluster-management-io/managed-serviceaccount/pull/116

🐛 Check if the token has expired (#116)

---

cmd/manager/main.go
pkg/addon/agent/controller/token.go
pkg/addon/agent/controller/token_test.go

cherry pick https://github.com/open-cluster-management-io/managed-serviceaccount/pull/120
Fixes #https://issues.redhat.com/browse/ACM-15033

Use the real expire time to check if the token should refresh (#120)

---

.tekton/managed-serviceaccount-mce-25-pull-request.yaml
.tekton/managed-serviceaccount-mce-25-push.yaml

This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263

fix(KONFLUX-3663): format PipelineRun files and upload SAST results

---

.tekton/OWNERS
.tekton/managed-serviceaccount-mce-26-pull-request.yaml
.tekton/managed-serviceaccount-mce-26-push.yaml

This PR:
- Formatting all tekton files
- Create an OWNERS file for tekton files

:seedling: [backplane-2.6] update konflux files

---

.tekton/OWNERS
.tekton/managed-serviceaccount-mce-27-pull-request.yaml
.tekton/managed-serviceaccount-mce-27-push.yaml

This PR:
- Formatting all tekton files
- Create an OWNERS file for tekton files

:seedling: [backplane-2.7] update konflux files

---

.github/renovate.json

Add Renovate configuration, set the Dockerfile we want renovate to update to Dockerfile.rhtap
Fixes #

🌱 Add Renovate configuration

---

.github/renovate.json
.github/workflows/renovate-config-validator.yaml

- update .tekton and Dockerfile.rhtap for main branch, prevent conflict from the upstream
- stop updating for backplane-2.8
- add a renovate validator action
Fixes #

🌱 Update renovate config to stop updating packages for the backplane 2.8 branch

---

.github/renovate.json

Prevent the renovate bot from updating the legacy branches like https://github.com/stolostron/managed-serviceaccount/pull/234 and https://github.com/stolostron/managed-serviceaccount/pull/233
Fixes #

🌱 Exclude legacy branches from renovate

---

.github/renovate.json

- disable go mod update for the main branch
- reset recreateWhen from always(default) to never
- disable update for backplane branches(2.0 2.1 2.2 2.3 2.4) without konflux config
Fixes #

🌱 Update removate config to recreate never

---

.tekton/managed-serviceaccount-mce-28-pull-request.yaml
.tekton/managed-serviceaccount-mce-28-push.yaml

This PR:
- Update konflux CEL from main to backplane-2.8

:seedling: [backplane-2.8] update konflux files

---

.tekton/managed-serviceaccount-mce-29-pull-request.yaml
.tekton/managed-serviceaccount-mce-29-push.yaml

This PR:
- Formatting all tekton files
- Update konflux CEL from backplane-2.9 to main

:seedling: [main] update konflux files

---

.github/renovate.json

🌱 Update removate config to stop updationg tekton files for the current release

---

.github/renovate.json
.tekton/managed-serviceaccount-mce-29-pull-request.yaml
.tekton/managed-serviceaccount-mce-29-push.yaml

🌱 Modify Konflux config for migration

---

renovate.json

:seedling: Add configuration for indirect Go dependencies in Renovate

---

.tekton/managed-serviceaccount-mce-29-pull-request.yaml
.tekton/managed-serviceaccount-mce-29-push.yaml
vendor/github.com/onsi/gomega/CHANGELOG.md
vendor/github.com/onsi/gomega/gomega_dsl.go
vendor/github.com/onsi/gomega/internal/async_assertion.go
vendor/github.com/onsi/gomega/types/types.go
vendor/k8s.io/api/resource/v1alpha3/types.go
vendor/k8s.io/api/resource/v1beta1/types.go
vendor/k8s.io/apiserver/pkg/authentication/serviceaccount/util.go
vendor/modules.txt

This PR updates the Tekton pipeline configuration files to support multiarch builds (linux/x86_64, linux/arm64, linux/ppc64le, linux/s390x).

:seedling: feat(tekton): add multiarch build support to Tekton pipeline configs

---

.tekton/managed-serviceaccount-mce-29-pull-request.yaml
.tekton/managed-serviceaccount-mce-29-push.yaml

Fixes https://issues.redhat.com/browse/ACM-21424

:seedling: Update konflux rpms-signature-scan bundle.

---

.tekton/managed-serviceaccount-mce-29-pull-request.yaml
.tekton/managed-serviceaccount-mce-29-push.yaml

[bp-2.9] Update tekton images

---

.tekton/managed-serviceaccount-mce-210-pull-request.yaml
.tekton/managed-serviceaccount-mce-210-push.yaml

🌱 Update common pipeline to common_mce_2.10.yaml

---

.tekton/managed-serviceaccount-mce-210-push.yaml

Use https://github.com/stolostron/managed-serviceaccount/pull/376 to send a Slack notification when push execution failed
Fixes #

✨ Send a slack notification when push execution failed

---

.tekton/managed-serviceaccount-mce-210-push.yaml

🌱 remove unnecessary slack notification parameters
